### PR TITLE
Backport rust-secp 284 and 422

### LINKED ISSUE #47: Wasm build fails
See: https://github.com/rust-bitcoin/rust-secp256k1/issues/419 for more context

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #47

(Actually I believe 47 is already fixed, but this re-enables the test in CI so we can be sure.)

Easiest way to review this is probably to add rust-secp as a remote and then use `range-diff` to see how my versions of the commits change from those in the PR. I have provided commit IDs in my commit messages.

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @sanket1729 let's get this in

File: contrib/test.sh [hunk 1]
```diff
@@ -59,6 +59,7 @@ fi
 
 # Address Sanitizer
 if [ "$DO_ASAN" = true ]; then
+    clang --version
```
Comment (sanket1729) [inline contrib/test.sh:62]: There is also another diff here at lin 55:
```diff
 if [ "$DO_WASM" = true ]; then
-    clang --version
+    clang-9 --version
```

**Review by sanket1729 — APPROVED** [review]
ACK b0a1a693bb6c4c83ae3e8bd974afa5d66d0217e5. Ignore the comment about clang-9, looks like it is not need for this secp-zkp CI
